contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #proteogenomicsdb channel"
    url: https://nfcore.slack.com/channels/proteogenomicsdb
    about: Discussion about the nf-core/proteogenomicsdb pipeline
