cosmic-to-proteindb:
   filter_info:
      filter_column: 'Histology subtype 1'
      accepted_values: "all"
      split_by_filter_column: False
logger:
  formatters:
    DEBUG: "%(asctime)s [%(levelname)7s][%(name)48s][%(module)32s, %(lineno)4s] %(message)s"
    INFO: "%(asctime)s [%(levelname)7s][%(name)48s] %(message)s"
  loglevel: DEBUG
